/*
  # Seed real 2026 running/cycling events — Hyderabad, Bengaluru, Chennai, Mumbai

  Comprehensive event data with real poster images, contact info, and website URLs.
  Includes past events (Jan–Mar 2026) and upcoming events through Dec 2026.
  All events set to 'approved' status.
  Also adds Chennai to the cities table.
*/

-- Add Chennai to cities if not already present
INSERT INTO cities (name, event_count, image_url)
SELECT 'Chennai', 10, 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?q=80&w=600&auto=format&fit=crop'
WHERE NOT EXISTS (SELECT 1 FROM cities WHERE name = 'Chennai');

-- Update city event counts
UPDATE cities SET event_count = 16 WHERE name = 'Mumbai';
UPDATE cities SET event_count = 16 WHERE name = 'Bengaluru';
UPDATE cities SET event_count = 11 WHERE name = 'Hyderabad';
UPDATE cities SET event_count = 10 WHERE name = 'Chennai';

-- Delete existing seed events to avoid duplicates on re-run
DELETE FROM events WHERE organizer_id IS NULL AND status = 'approved';

-- =============================================
-- HYDERABAD EVENTS (11 events)
-- =============================================

INSERT INTO events (title, description, date, sport, distance_tags, category_tags, price, city, state, image_url, interested_count, status, website_url, contact_info)
VALUES
(
  'Hyderabad 10K Run 2026',
  'Kick off the new year at People''s Plaza on Necklace Road, one of the city''s most scenic running routes along Hussain Sagar Lake. Over 5,000 runners participate annually with chip timing, finisher medals, and refreshments for all.',
  '2026-01-04',
  'running',
  ARRAY['5K', '10K'],
  ARRAY['Road Run'],
  720,
  'Hyderabad',
  'IN',
  'https://images.unsplash.com/photo-1605218427368-35b0185e927f?q=80&w=600&auto=format&fit=crop',
  320,
  'approved',
  'https://www.hyderabad10krun.com/',
  'Email: contact@nebsports.in | Phone: +91 81509 44084'
),
(
  'Zydus Pinkathon Hyderabad 2026',
  'India''s biggest women''s run returns to Hyderabad for its 6th edition at People''s Plaza, drawing 5,000 women participants. Raises awareness for breast cancer screening and women''s health.',
  '2026-02-15',
  'running',
  ARRAY['3K', '5K', '10K'],
  ARRAY['Road Run', 'Fun Run'],
  1080,
  'Hyderabad',
  'IN',
  'https://pinkathon.life/wp-content/uploads/2025/09/Pinkathon-ILU-1024x498.png',
  480,
  'approved',
  'https://pinkathon.life/hyderabad/',
  'Email: Info@pinkathon.life'
),
(
  'Hyderabad Runners Club Run 2026',
  'The 17th edition of the Club Run organized by Hyderabad Runners Society at University of Hyderabad campus. India''s largest running club hosts the first fully-supported half marathon of the year.',
  '2026-02-15',
  'running',
  ARRAY['10K', 'Half Marathon'],
  ARRAY['Road Run'],
  990,
  'Hyderabad',
  'IN',
  'https://hyderabadrunners.com/wp-content/uploads/2026/03/hyderabad_runners_og_cta.jpg',
  350,
  'approved',
  'https://hyderabadrunners.com/events/',
  'Instagram: @hyderabadrunnerssociety | Website: hyderabadrunners.com'
),
(
  'Happiest Minds Run Hyderabad 2026',
  'The 6th edition of Happiest Minds Technologies'' running celebration at Gachibowli Stadium. Proceeds support children living with Type 1 Diabetes through Idhayangal Charitable Trust. Includes T-shirt, medal, Zumba, breakfast.',
  '2026-02-15',
  'running',
  ARRAY['2K', '5K', '10K'],
  ARRAY['Road Run', 'Fun Run'],
  540,
  'Hyderabad',
  'IN',
  'https://images.unsplash.com/photo-1552674605-46d532b2e591?q=80&w=600&auto=format&fit=crop',
  180,
  'approved',
  'https://www.happiestminds.com/events/happiest-minds-run/',
  'Website: happiestminds.com'
),
(
  'Rapido Hyderabad Heritage Run 2026',
  'The inaugural Heritage Run organized by Telangana Tourism and Rapido. The 21-km Half Marathon starts at iconic Charminar and finishes at historic Qutb Shahi Tombs, passing through Golconda Fort.',
  '2026-02-22',
  'running',
  ARRAY['5K', '10K', 'Half Marathon'],
  ARRAY['Road Run'],
  0,
  'Hyderabad',
  'IN',
  'https://images.unsplash.com/photo-1572097662444-81c04ee21e0c?q=80&w=600&auto=format&fit=crop',
  420,
  'approved',
  'https://hellohyderabad.org/events/hyderabad-heritage-run-2026-february-22/',
  'Telangana Tourism Department | Twitter: @TravelTelangana'
),
(
  'Freshathon Shine India Hyderabad 2026',
  'Community wellness initiative at Gachibowli Stadium. Partners with Ray of Sunshine Foundation, directing funds toward prostate cancer treatment, CPR training, and supporting underprivileged athletes.',
  '2026-02-22',
  'running',
  ARRAY['3K', '5K', '10K'],
  ARRAY['Road Run', 'Fun Run'],
  1080,
  'Hyderabad',
  'IN',
  'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?q=80&w=600&auto=format&fit=crop',
  200,
  'approved',
  'https://freshathon.in/',
  'Website: freshathon.in'
),
(
  'SBI Green Marathon Hyderabad 2026',
  'Part of the nationwide SBI Green Marathon series promoting sustainability and fitness. Timed categories across 5K, 10K, and Half Marathon with timing chips and finisher medals.',
  '2026-03-08',
  'running',
  ARRAY['5K', '10K', 'Half Marathon'],
  ARRAY['Road Run'],
  1170,
  'Hyderabad',
  'IN',
  'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?q=80&w=600&auto=format&fit=crop',
  290,
  'approved',
  'https://greenmarathon.in/cities/hyderabad.html',
  'Website: greenmarathon.in'
),
(
  'The Village Run Hyderabad 2026',
  'A unique running event in rural outskirts near Shamshabad. The course takes runners through rustic village landscapes offering a refreshing change from urban road runs.',
  '2026-04-05',
  'running',
  ARRAY['5K', '10K', '16K', 'Half Marathon'],
  ARRAY['Trail Run', 'Road Run'],
  810,
  'Hyderabad',
  'IN',
  'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?q=80&w=600&auto=format&fit=crop',
  180,
  'approved',
  '',
  'Narender Reddy G | Phone: 9701055611'
),
(
  'Freedom Hyderabad 10K Run 2026',
  'One of Hyderabad''s most anticipated annual running events held on Independence Day at People''s Plaza, Necklace Road. The 17th edition celebrates national pride through fitness.',
  '2026-08-15',
  'running',
  ARRAY['10K'],
  ARRAY['Road Run'],
  810,
  'Hyderabad',
  'IN',
  'https://images.unsplash.com/photo-1532444458054-01a7dd3e9fca?q=80&w=600&auto=format&fit=crop',
  550,
  'approved',
  'https://www.hyderabad10krun.com/',
  'Instagram: @hyd10krun'
),
(
  'NMDC Hyderabad Marathon 2026',
  'The flagship running event of Hyderabad and India''s second-largest marathon. AIMS-certified and World Athletics Label Race attracting over 25,500 participants at GMC Balayogi Stadium.',
  '2026-08-30',
  'running',
  ARRAY['5K', '10K', 'Half Marathon', 'Full Marathon'],
  ARRAY['Road Run'],
  3420,
  'Hyderabad',
  'IN',
  'https://nmdchyderabadmarathon.com/assets/images/banners/NHM_15.png',
  1250,
  'approved',
  'https://nmdchyderabadmarathon.com/',
  'Email: info@marathonhyderabad.com | Phone: +91 9676471678 | Instagram: @nmdchyderabadmarathon'
),
(
  'Hyderabad Hitec Marathon 2026',
  'Organized by NEB Sports at Gachibowli Stadium, the Hyderabad Hitec Marathon offers four race categories through the HITEC City corridor. One of the city''s major marathon events.',
  '2026-11-01',
  'running',
  ARRAY['5K', '10K', 'Half Marathon', 'Full Marathon'],
  ARRAY['Road Run'],
  3330,
  'Hyderabad',
  'IN',
  'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?q=80&w=600&auto=format&fit=crop',
  680,
  'approved',
  'https://hyderabadhitecmarathon.com/',
  'Phone: +91 9206265087 | Email: support@hyderabadhalfmarathon.in'
),

-- =============================================
-- BENGALURU EVENTS (16 events)
-- =============================================

(
  'Happiest Minds Run Bengaluru 2026',
  'Held at St. Joseph''s Indian High School Ground, opposite UB City. A spirited celebration by Happiest Minds Technologies supporting children with Type 1 Diabetes. Includes T-shirt, medal, breakfast, Zumba.',
  '2026-01-18',
  'running',
  ARRAY['2K', '5K', '10K'],
  ARRAY['Road Run', 'Fun Run'],
  540,
  'Bengaluru',
  'IN',
  'https://images.unsplash.com/photo-1533561797500-4fad4750814e?q=80&w=600&auto=format&fit=crop',
  220,
  'approved',
  'https://www.happiestminds.com/events/happiest-minds-run/',
  'Website: happiestminds.com'
),
(
  'Marathon Utsava 2026',
  'A vibrant running festival for all types of runners in Bengaluru. Half marathon participants must have previously completed a 10K or higher in an officially timed event.',
  '2026-01-25',
  'running',
  ARRAY['3K', '5K', '10K', 'Half Marathon'],
  ARRAY['Road Run', 'Fun Run'],
  1260,
  'Bengaluru',
  'IN',
  'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?q=80&w=600&auto=format&fit=crop',
  310,
  'approved',
  '',
  'Registration via IndiaRunning.com or Townscript'
),
(
  'Bengaluru Mountain Festival 2026',
  'A challenging trail run traversing four rocky hills with stair climbs at Avati near Devanahalli. Over 3,000 participants. Includes full route marking, feed stops, medical support.',
  '2026-01-25',
  'trail',
  ARRAY['5K', '10K', 'Half Marathon'],
  ARRAY['Trail Run', 'Mountain'],
  1710,
  'Bengaluru',
  'IN',
  'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?q=80&w=600&auto=format&fit=crop',
  360,
  'approved',
  'https://bmftrails.com/bmf/',
  'Website: bmftrails.com'
),
(
  'BBCh26 MTB Race #01 2026',
  'The first race of the 2026 Bangalore Bicycle Championships — India''s longest-running amateur cycle racing platform. MTB XC format with ~4.1 km laps. Event sold out.',
  '2026-01-25',
  'cycling',
  ARRAY['4.1K laps'],
  ARRAY['Cycling'],
  1080,
  'Bengaluru',
  'IN',
  'https://images.unsplash.com/photo-1541625602330-2277a4c46182?q=80&w=600&auto=format&fit=crop',
  190,
  'approved',
  'https://bbch.in/',
  'Instagram: @bangalorebicyclechampionships'
),
(
  'Tuffman Bengaluru Half Marathon 2026',
  'Held on scenic NICE Road, the Tuffman Half Marathon offers timed events for serious runners and non-timed categories for beginners. Includes race bag, timing bib, finisher medal.',
  '2026-02-01',
  'running',
  ARRAY['3K', '5K', '10K', 'Half Marathon'],
  ARRAY['Road Run'],
  1710,
  'Bengaluru',
  'IN',
  'http://tuffmanindia.com/images/hero.jpg',
  380,
  'approved',
  'https://www.tuffmanindia.com/races/bengaluru-half-marathon.html',
  'Email: info@tuffmanindia.com'
),
(
  'HCL Cyclothon Bengaluru 2026',
  'The debut Bengaluru edition of HCL Cyclothon, organized with the Cycling Federation of India on NICE Road with a Rs 30 lakh prize purse. 1,850+ cyclists.',
  '2026-02-08',
  'cycling',
  ARRAY['16K', '32K', '50K'],
  ARRAY['Cycling'],
  1710,
  'Bengaluru',
  'IN',
  'https://images.unsplash.com/photo-1517649763962-0c623066013b?q=80&w=600&auto=format&fit=crop',
  420,
  'approved',
  'https://hclcyclothon.com/bengaluru-edition/',
  'Website: hclcyclothon.com'
),
(
  'Kaveri Trail Marathon 2026',
  'India''s oldest trail marathon near Kodagu, Karnataka. Races start and finish next to Ranganathittu Bird Sanctuary, following the canal of the River Kaveri through the Western Ghats.',
  '2026-02-14',
  'trail',
  ARRAY['5K', '10K', 'Half Marathon', 'Full Marathon'],
  ARRAY['Trail Run'],
  2700,
  'Bengaluru',
  'IN',
  'https://kaveritrailmarathon.com/wp-content/uploads/2025/11/THANK-YOU-FOR-PARTICIPATING-BAN-WEB.png',
  520,
  'approved',
  'https://kaveritrailmarathon.com/',
  'Website: kaveritrailmarathon.com'
),
(
  'Karnataka State Police Run 2026',
  'The 3rd edition themed ''Namma Police Namma Hemme'' (Our Police Our Pride) at Vidhana Soudha. Promotes fitness and drug-free life awareness. Over 10,000 participants.',
  '2026-03-01',
  'running',
  ARRAY['5K', '10K'],
  ARRAY['Road Run'],
  810,
  'Bengaluru',
  'IN',
  'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?q=80&w=600&auto=format&fit=crop',
  340,
  'approved',
  '',
  'Instagram: @karnatakastatepolicerun'
),
(
  'Namma Power Run 2026',
  'Held on NICE Road, this event honours the legacy of the late Kannada actor Dr. Puneeth Rajkumar. Organized by Sutra Fitness with the Dr. Puneeth Rajkumar Charitable Trust.',
  '2026-03-15',
  'running',
  ARRAY['5K', '10K', 'Half Marathon'],
  ARRAY['Road Run'],
  1350,
  'Bengaluru',
  'IN',
  'https://nammapowerrun.com/wp-content/uploads/2023/12/logo.png',
  340,
  'approved',
  'https://nammapowerrun.com/',
  'Social: @nammapowerrun | Website: nammapowerrun.com'
),
(
  'TCS World 10K Bengaluru 2026',
  'One of the world''s premier 10K road races and Bengaluru''s flagship running event. The 18th edition attracts elite international athletes and thousands of citizen runners.',
  '2026-04-26',
  'running',
  ARRAY['5K', '10K'],
  ARRAY['Road Run'],
  2520,
  'Bengaluru',
  'IN',
  'https://tcsworld10k.procam.in/_next/static/media/ProcamBeng_OG.f327e265.jpg',
  1800,
  'approved',
  'https://tcsworld10k.procam.in/',
  'Email: tcsworld10k@procam.in | Phone: +91 80 41739955 | Instagram: @tcsw10k'
),
(
  'Wings for Life World Run Bangalore 2026',
  'A global running event by Red Bull where all participants worldwide start simultaneously and run until a virtual catcher car overtakes them. 100% of entry fees go to spinal cord injury research.',
  '2026-05-10',
  'running',
  ARRAY['Unlimited'],
  ARRAY['Road Run', 'Fun Run'],
  1350,
  'Bengaluru',
  'IN',
  'https://www.wingsforlifeworldrun.com/image-service/uploads/events/2026/bangalore/are_header.c140dfd2ab5c69da496516deeeb1630a.jpg?action=resize&fit=cover&width=1200&height=630',
  620,
  'approved',
  'https://www.wingsforlifeworldrun.com/en/locations/bangalore',
  'Website: wingsforlifeworldrun.com'
),
(
  'Bangalore Ultra Marathon 2026',
  'India''s oldest Ultra Marathon held on scenic outskirts of Bengaluru. The undulating 12.5K out-and-back trail is both scenic and challenging. Draws the largest congregation of ultra-runners.',
  '2026-07-26',
  'trail',
  ARRAY['12.5K', '25K', '50K'],
  ARRAY['Trail Run', 'Ultra'],
  2520,
  'Bengaluru',
  'IN',
  'https://bangaloreultra.com/wp-content/uploads/2025/10/Regn-are-open_FB-Cover-1.jpg',
  440,
  'approved',
  'https://bangaloreultra.com/',
  'Phone: 9206265087 | Email: support@bengalurumarathon.in'
),
(
  'Wipro Bengaluru Marathon 2026',
  'The city''s premier AIMS-certified full marathon through Bengaluru''s major thoroughfares. Features full marathon, half marathon, 10K charity run, and 5K fun run.',
  '2026-11-08',
  'running',
  ARRAY['5K', '10K', 'Half Marathon', 'Full Marathon'],
  ARRAY['Road Run'],
  2250,
  'Bengaluru',
  'IN',
  'https://bengalurumarathon.in/images/web_banner_mobile.webp',
  950,
  'approved',
  'https://bengalurumarathon.in/',
  'Email: support@bengalurumarathon.in | Instagram: @wipro_bengaluru_marathon'
),
(
  'Tour of Karnataka 2026',
  'India''s biggest and most premium fully supported cycling tour. Covers 523 km through Chikkamagaluru, Belur, Udupi, Agumbe, Kuduremukh over 6 days. Limited to 150 participants.',
  '2026-11-17',
  'cycling',
  ARRAY['523 km'],
  ARRAY['Cycling', 'Multi-Stage'],
  56250,
  'Bengaluru',
  'IN',
  'https://tourofkarnataka.com/images/og.jpeg',
  280,
  'approved',
  'https://www.tourofkarnataka.com/',
  'Instagram: @tourofkarnataka | Website: tourofkarnataka.com'
),
(
  'Bengaluru Midnight Marathon 2026',
  'Asia''s only Midnight Marathon, created by Rotary Bangalore IT Corridor in 2007. The AIMS-certified race at KTPO Whitefield sees runners race through the night under the stars.',
  '2026-12-05',
  'running',
  ARRAY['5K', '10K', 'Half Marathon', 'Full Marathon'],
  ARRAY['Road Run', 'Night Run'],
  2160,
  'Bengaluru',
  'IN',
  'https://images.unsplash.com/photo-1552674605-5d2178b84916?q=80&w=600&auto=format&fit=crop',
  750,
  'approved',
  'https://bangalore.bharatmidnightmarathon.run/',
  'Email: info@midnightmarathon.in | Instagram: @bengalurumidnightmarathon'
),

-- =============================================
-- CHENNAI EVENTS (10 events)
-- =============================================

(
  'Freshworks Chennai Marathon 2026',
  'India''s premier road marathon with over 28,500 runners from 16+ countries. AIMS-certified course starts at iconic Napier Bridge, traces Marina Beach along scenic ECR. Flat coastal terrain ideal for PRs.',
  '2026-01-04',
  'running',
  ARRAY['10K', 'Half Marathon', '20 Miler', 'Full Marathon'],
  ARRAY['Road Run'],
  1530,
  'Chennai',
  'IN',
  'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?q=80&w=600&auto=format&fit=crop',
  1400,
  'approved',
  'https://www.thechennaimarathon.com/',
  'Email: corporateregistration@chennairunners.in | Instagram: @thechennaimarathon'
),
(
  'K10K Cancer Awareness Run 2026',
  'Organized by Kauvery Hospital to spread awareness about cancer and raise funds for underprivileged patients at Besant Nagar. Bib expo at Decathlon Pondy Bazaar the day before.',
  '2026-01-31',
  'running',
  ARRAY['5K', '10K'],
  ARRAY['Road Run', 'Fun Run'],
  900,
  'Chennai',
  'IN',
  'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?q=80&w=600&auto=format&fit=crop',
  260,
  'approved',
  'https://k10k.run/',
  'Phone: +91 8148099099 | Email: communication@kauveryhospital.com'
),
(
  'Auroville Marathon 2026',
  'A non-commercial community marathon held annually in the City of Dawn. Organized purely for the joy of running with no prize money — all finishers are winners. AIMS certified course.',
  '2026-02-08',
  'running',
  ARRAY['10K', 'Half Marathon', 'Full Marathon'],
  ARRAY['Road Run'],
  2160,
  'Chennai',
  'IN',
  'https://images.unsplash.com/photo-1513593771513-7b58b6c4af38?q=80&w=600&auto=format&fit=crop',
  380,
  'approved',
  'https://www.aurovillemarathon.com/',
  'Email: marathon@auroville.org.in'
),
(
  'SBI Green Marathon Chennai 2026',
  'An SBI initiative promoting environmental sustainability and healthier lifestyles at G Square Tranquil, Uthandi. Age eligibility 5+ for 5K and 18+ for longer distances.',
  '2026-03-01',
  'running',
  ARRAY['5K', '10K', 'Half Marathon'],
  ARRAY['Road Run'],
  1350,
  'Chennai',
  'IN',
  'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?q=80&w=600&auto=format&fit=crop',
  310,
  'approved',
  'https://greenmarathon.in/cities/chennai.html',
  'Instagram: @sbigreenmarathon | Website: greenmarathon.in'
),
(
  'Pink Sakhi Run Chennai 2026',
  'A Women''s Day run celebrating fitness, courage, and togetherness at Olcott School, Besant Nagar. Features a unique 3K x 4 Relay format for team participation.',
  '2026-03-08',
  'running',
  ARRAY['3K', '5K', '10K'],
  ARRAY['Road Run', 'Fun Run'],
  900,
  'Chennai',
  'IN',
  'https://images.unsplash.com/photo-1552674605-46d532b2e591?q=80&w=600&auto=format&fit=crop',
  280,
  'approved',
  '',
  'Registration via IndiaRunning.com'
),
(
  'Azurap TN Marathon Chennai 2026',
  'The 5th edition champions the cause of women''s safety at Olcott Memorial School, Besant Nagar. Starts with yoga and Zumba at 4:30 AM followed by staggered category starts.',
  '2026-06-28',
  'running',
  ARRAY['3K', '5K', '10K'],
  ARRAY['Road Run', 'Fun Run'],
  990,
  'Chennai',
  'IN',
  'https://images.unsplash.com/photo-1532444458054-01a7dd3e9fca?q=80&w=600&auto=format&fit=crop',
  220,
  'approved',
  '',
  'Email: tnmarathon23@gmail.com | Phone: +91 82488 68900'
),
(
  'Hexaware Dream Runners Half Marathon 2026',
  'One of Chennai''s most established half marathons. The 15th edition promotes wellness and active lifestyles. Free structured training programs organized across Chennai.',
  '2026-07-19',
  'running',
  ARRAY['10K', 'Half Marathon'],
  ARRAY['Road Run'],
  1800,
  'Chennai',
  'IN',
  'https://dreamrunners.in/wp-content/uploads/2022/09/DRHM-2026-schedule-post-2.png',
  480,
  'approved',
  'https://dreamrunners.in/',
  'Email: info@dreamrunners.in | Instagram: @dream.runners.chennai'
),
(
  'HCL Cyclothon Chennai 2026',
  'India''s highest-prize cycling event along the scenic ECR starting from Mayajaal Multiplex. 2,000+ cyclists with categories for professionals, amateurs, and recreational. Rs 33.6 lakh prize pool.',
  '2026-09-20',
  'cycling',
  ARRAY['24K', '50K'],
  ARRAY['Cycling'],
  1890,
  'Chennai',
  'IN',
  'https://images.unsplash.com/photo-1517649763962-0c623066013b?q=80&w=600&auto=format&fit=crop',
  390,
  'approved',
  'https://hclcyclothon.com/',
  'Website: hclcyclothon.com'
),
(
  'Chennai Trail Marathon 2026',
  'Chennai''s dedicated trail running event offering an off-road experience. Part of the Chennai Runners qualifier series counting toward the Grand Slam Finale.',
  '2026-12-06',
  'trail',
  ARRAY['10K', 'Half Marathon', 'Full Marathon'],
  ARRAY['Trail Run'],
  2250,
  'Chennai',
  'IN',
  'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?q=80&w=600&auto=format&fit=crop',
  340,
  'approved',
  'https://chennaitrailmarathon.com/',
  'Organizer: Chennai Runners | Instagram: @chennairunners'
),

-- =============================================
-- MUMBAI EVENTS (16 events)
-- =============================================

(
  'Navi Mumbai 15K Run 2026',
  'Held at Palm Beach Road, Navi Mumbai. Organized to raise funds for Rotary''s Touching Little Hearts project providing financial assistance for children''s congenital heart conditions.',
  '2026-01-04',
  'running',
  ARRAY['5K', '10K', '15K'],
  ARRAY['Road Run'],
  1530,
  'Mumbai',
  'IN',
  'https://images.unsplash.com/photo-1533561797500-4fad4750814e?q=80&w=600&auto=format&fit=crop',
  240,
  'approved',
  '',
  'Registration via IndiaRunning.com'
),
(
  'Tata Mumbai Marathon 2026',
  'Asia''s largest marathon and India''s biggest charity running platform. Route passes through CSMT, Marine Drive, Bandra-Worli Sea Link, and Gateway of India. Over 70,000 runners.',
  '2026-01-18',
  'running',
  ARRAY['6K', '10K', 'Half Marathon', 'Full Marathon'],
  ARRAY['Road Run'],
  3870,
  'Mumbai',
  'IN',
  'https://tatamumbaimarathon.procam.in/_next/static/media/og-image.1ea55f10.jpg',
  2500,
  'approved',
  'https://tatamumbaimarathon.procam.in/',
  'Email: tatamumbaimarathon@procam.in | Phone: +91 22 4202 0200 | WhatsApp: 8976994484'
),
(
  'Mumbai Half Marathon Bandra 2026',
  'Organized by Omega Events at Bandra Fort Garden along the coastal line. Runners experience a scenic route along the sea. Includes T-shirt, finisher medal, breakfast, timing certificate.',
  '2026-02-01',
  'running',
  ARRAY['5K', '10K', 'Half Marathon'],
  ARRAY['Road Run', 'Fun Run'],
  990,
  'Mumbai',
  'IN',
  'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?q=80&w=600&auto=format&fit=crop',
  380,
  'approved',
  'https://mumbaihalfmarathon.com/',
  'Website: mumbaihalfmarathon.com'
),
(
  'Wesness Women''s 5K Fun Run Mumbai 2026',
  'A women-only celebration run at Tata Garden, Mumbai. Post-run celebration features interactive photo booths, a nail bar, DJ sets, and breast cancer awareness talk.',
  '2026-02-08',
  'running',
  ARRAY['5K'],
  ARRAY['Fun Run'],
  990,
  'Mumbai',
  'IN',
  'https://images.unsplash.com/photo-1552674605-46d532b2e591?q=80&w=600&auto=format&fit=crop',
  190,
  'approved',
  '',
  'Registration via IndiaRunning.com and BhaagoIndia.com'
),
(
  'Run For Hope Mumbai 2026',
  'Part of Project Hope supporting shelter homes helping children and families battling cancer. Includes race bib, finisher medal, event T-shirt, hydration, medical support.',
  '2026-02-15',
  'running',
  ARRAY['2K', '5K'],
  ARRAY['Road Run', 'Fun Run'],
  450,
  'Mumbai',
  'IN',
  'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?q=80&w=600&auto=format&fit=crop',
  150,
  'approved',
  '',
  'Registration via IndiaRunning.com'
),
(
  'Lotus Juhu Half Marathon 2026',
  'One of Mumbai''s most loved running events since 2017, supporting life-saving paediatric heart surgeries for underprivileged children. Starts from JVPD Ground in Juhu.',
  '2026-03-01',
  'running',
  ARRAY['4K', '5K', '10K', 'Half Marathon'],
  ARRAY['Road Run', 'Fun Run'],
  2340,
  'Mumbai',
  'IN',
  'https://images.unsplash.com/photo-1533561797500-4fad4750814e?q=80&w=600&auto=format&fit=crop',
  460,
  'approved',
  'https://juhuhalfmarathon.org/',
  'Instagram: @juhuhalfmarathon'
),
(
  'Kharghar Marathon 2026',
  'Held in Navi Mumbai supporting setting up a dialysis centre and providing filters for Thalassemia children. Organized by The Cause Travellers, an 80G/12A/CSR-1 certified NGO.',
  '2026-04-05',
  'running',
  ARRAY['3K', '5K', '10K', 'Half Marathon'],
  ARRAY['Road Run', 'Fun Run'],
  810,
  'Mumbai',
  'IN',
  'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?q=80&w=600&auto=format&fit=crop',
  290,
  'approved',
  '',
  'Organizer: The Cause Travellers Social Welfare Organisation'
),
(
  'Mumbai Midnight Marathon 2026',
  'One of Mumbai''s unique nighttime running events offering the thrill of running through illuminated streets after dark. Cooler temperatures make it popular during warmer months.',
  '2026-05-23',
  'running',
  ARRAY['5K', '10K', 'Half Marathon'],
  ARRAY['Road Run', 'Night Run'],
  2250,
  'Mumbai',
  'IN',
  'https://images.unsplash.com/photo-1552674605-5d2178b84916?q=80&w=600&auto=format&fit=crop',
  380,
  'approved',
  '',
  'NEB Sports: contact@nebsports.in'
),
(
  'Monsoon Ultra Mumbai Trails 2026',
  'Set in Sanjay Gandhi National Park during monsoon season. Trails past waterfalls, ancient Kanheri Caves, and dense tropical forest. One of the only ultramarathon events within Mumbai city limits.',
  '2026-06-06',
  'trail',
  ARRAY['20K', '35K', '50K'],
  ARRAY['Trail Run', 'Ultra'],
  4500,
  'Mumbai',
  'IN',
  'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?q=80&w=600&auto=format&fit=crop',
  310,
  'approved',
  'https://monsoonultra.com/',
  'Location: Sanjay Gandhi National Park, Borivali'
),
(
  'Freedom Run Mumbai 2026',
  'Celebrate Independence Day through fitness with water stations, energy drinks, and first aid every 2 km. Top 3 male and female runners in 5K and 10K receive awards.',
  '2026-08-15',
  'running',
  ARRAY['3K', '5K', '10K', 'Half Marathon'],
  ARRAY['Road Run'],
  1170,
  'Mumbai',
  'IN',
  'https://images.unsplash.com/photo-1532444458054-01a7dd3e9fca?q=80&w=600&auto=format&fit=crop',
  350,
  'approved',
  'https://freedomrunmumbai.com/',
  'Website: freedomrunmumbai.com'
),
(
  'AFLI Mumbai Half Marathon 2026',
  'The 9th edition organized by NEB Sports and sponsored by Ageas Federal Life Insurance. One of Mumbai''s premier half marathon events with chip timing and professional race management.',
  '2026-08-30',
  'running',
  ARRAY['5K', '10K', 'Half Marathon'],
  ARRAY['Road Run'],
  2790,
  'Mumbai',
  'IN',
  'https://images.unsplash.com/photo-1513593771513-7b58b6c4af38?q=80&w=600&auto=format&fit=crop',
  520,
  'approved',
  'https://mumbaihalfmarathon.com/',
  'Email: support@mumbaihalfmarathon.com | Phone: +91 9206265087'
),
(
  'Pinkathon Mumbai 2026',
  'India''s biggest women-only run raises awareness about breast cancer and women''s health. Founded by Milind Soman, the Mumbai edition attracts thousands of women runners.',
  '2026-09-13',
  'running',
  ARRAY['3K', '5K', '10K', 'Half Marathon'],
  ARRAY['Road Run', 'Fun Run'],
  1710,
  'Mumbai',
  'IN',
  'https://pinkathon.life/wp-content/uploads/2025/09/Pinkathon-ILU-1024x498.png',
  680,
  'approved',
  'https://pinkathon.life/mumbai/',
  'Email: info@pinkathon.life | Instagram: @pinkathonindia'
),
(
  'Vasai-Virar Marathon 2026',
  'One of the largest marathon events in the Mumbai metro region, regularly drawing over 20,000 participants. Attracts elite national athletes with substantial prize money.',
  '2026-12-06',
  'running',
  ARRAY['3K', '5K', '10K', 'Half Marathon', 'Full Marathon'],
  ARRAY['Road Run'],
  990,
  'Mumbai',
  'IN',
  'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?q=80&w=600&auto=format&fit=crop',
  1100,
  'approved',
  'https://vvmm.in/',
  'Vasai-Virar City Municipal Corporation Sports Department'
),
(
  'Jio Mumbai Cyclothon 2026',
  'India''s grandest sustainability-themed cyclothon at BKC. Diverse categories from casual 10K joy ride to competitive 100K, plus elite CFI race and 5K wheelchair race. Over 6,000 cyclists expected.',
  '2026-12-13',
  'cycling',
  ARRAY['10K', '25K', '50K', '100K'],
  ARRAY['Cycling'],
  2790,
  'Mumbai',
  'IN',
  'https://images.unsplash.com/photo-1517649763962-0c623066013b?q=80&w=600&auto=format&fit=crop',
  480,
  'approved',
  'https://www.champendurance.com/',
  'Organizer: Champ Endurance | Instagram: @jiomumbaicyclothon'
);
